In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df=pd.read_csv('dft-road-casualty-statistics-collision-last-5-years.csv')

In [4]:
df

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,2021170H10421,2021,170H10421,447098.0,532997.0,-1.270905,54.689833,17,3,2,...,0,0,2,1,2,E01011959,-1,0,0.293588,0.706412
1,2021170H11231,2021,170H11231,450486.0,533118.0,-1.218333,54.690592,17,3,2,...,0,0,1,2,2,E01011973,-1,0,0.017448,0.982552
2,2020170M11750,2020,170M11750,449694.0,519733.0,-1.232884,54.570397,17,3,2,...,0,0,1,1,2,E01012092,-1,0,0.128730,0.871270
3,2021170M31761,2021,170M31761,449744.0,514217.0,-1.233040,54.520825,17,3,1,...,0,0,2,1,2,E01032553,-1,0,0.182698,0.817302
4,2021170S10441,2021,170S10441,445971.0,520834.0,-1.290292,54.580641,17,3,3,...,0,13,2,1,1,E01012258,-1,0,0.016094,0.983906
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503470,202163D072221,2021,63D072221,317791.0,238031.0,-3.199828,52.034574,63,2,1,...,0,0,2,1,-1,W01000445,-1,0,1.000000,0.000000
503471,202263D008922,2022,63D008922,308640.0,253525.0,-3.337343,52.172396,63,3,1,...,0,0,2,1,-1,W01000459,-1,0,0.096816,0.903184
503472,202263D058922,2022,63D058922,311937.0,234115.0,-3.284127,51.998470,63,3,2,...,0,0,2,1,-1,W01000440,-1,0,0.088211,0.911789
503473,202363D007623,2023,63D007623,321327.0,304240.0,-3.163807,52.630192,63,2,1,...,0,0,2,1,-1,W01000498,-1,0,1.000000,0.000000
503474,2024631460061,2024,631460061,320423.0,312385.0,-3.179130,52.703260,63,2,3,...,-1,13,2,1,-1,W01000444,5,1,1.000000,0.000000

In [5]:
spatial_road_features = [
    "latitude",
    "longitude",
    "date",
    "speed_limit",
    "road_type",
    "time",
    "first_road_class",
    "first_road_number",
    "junction_detail",
    "junction_control",
    "second_road_class",
    "second_road_number",
    "pedestrian_crossing",
    "road_surface_conditions",
    "weather_conditions",
    "light_conditions",
    "carriageway_hazards",
    "urban_or_rural_area"
]

In [6]:
df1=df[spatial_road_features]

In [7]:
df1

,latitude,longitude,date,speed_limit,road_type,time,first_road_class,first_road_number,junction_detail,junction_control,second_road_class,second_road_number,pedestrian_crossing,road_surface_conditions,weather_conditions,light_conditions,carriageway_hazards,urban_or_rural_area
0,54.689833,-1.270905,22/05/2021,60,6,22:44,6,0,0,-1,0,-1,0,1,1,6,0,2
1,54.690592,-1.218333,20/10/2021,30,6,15:50,4,1277,16,2,5,0,0,1,1,1,0,1
2,54.570397,-1.232884,01/12/2020,20,6,18:00,6,0,16,4,6,0,0,1,1,4,0,1
3,54.520825,-1.233040,09/12/2021,40,6,16:55,5,0,0,-1,0,-1,0,2,1,4,0,2
4,54.580641,-1.290292,12/04/2021,70,3,09:02,3,19,0,-1,0,-1,0,1,1,1,13,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503470,52.034574,-3.199828,11/09/2021,60,6,01:15,6,0,0,-1,0,-1,0,1,1,6,0,2
503471,52.172396,-3.337343,04/02/2022,60,6,14:36,3,481,13,4,6,0,0,1,1,1,0,2
503472,51.998470,-3.284127,22/07/2022,60,6,15:15,3,470,16,4,3,438,0,1,1,1,0,2
503473,52.630192,-3.163807,27/01/2023,60,6,06:45,3,483,0,-1,0,-1,0,2,1,6,0,2
503474,52.703260,-3.179130,24/06/2024,60,6,17:00,3,490,13,4,6,0,0,1,1,1,13,2

In [8]:
df1.isnull().sum()

latitude                   65
longitude                  65
date                        0
speed_limit                 0
road_type                   0
time                        0
first_road_class            0
first_road_number           0
junction_detail             0
junction_control            0
second_road_class           0
second_road_number          0
pedestrian_crossing         0
road_surface_conditions     0
weather_conditions          0
light_conditions            0
carriageway_hazards         0
urban_or_rural_area         0
dtype: int64

In [9]:
df1=df1.dropna()

In [10]:
df1.isnull().sum()

latitude                   0
longitude                  0
date                       0
speed_limit                0
road_type                  0
time                       0
first_road_class           0
first_road_number          0
junction_detail            0
junction_control           0
second_road_class          0
second_road_number         0
pedestrian_crossing        0
road_surface_conditions    0
weather_conditions         0
light_conditions           0
carriageway_hazards        0
urban_or_rural_area        0
dtype: int64

In [11]:
df1

,latitude,longitude,date,speed_limit,road_type,time,first_road_class,first_road_number,junction_detail,junction_control,second_road_class,second_road_number,pedestrian_crossing,road_surface_conditions,weather_conditions,light_conditions,carriageway_hazards,urban_or_rural_area
0,54.689833,-1.270905,22/05/2021,60,6,22:44,6,0,0,-1,0,-1,0,1,1,6,0,2
1,54.690592,-1.218333,20/10/2021,30,6,15:50,4,1277,16,2,5,0,0,1,1,1,0,1
2,54.570397,-1.232884,01/12/2020,20,6,18:00,6,0,16,4,6,0,0,1,1,4,0,1
3,54.520825,-1.233040,09/12/2021,40,6,16:55,5,0,0,-1,0,-1,0,2,1,4,0,2
4,54.580641,-1.290292,12/04/2021,70,3,09:02,3,19,0,-1,0,-1,0,1,1,1,13,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503470,52.034574,-3.199828,11/09/2021,60,6,01:15,6,0,0,-1,0,-1,0,1,1,6,0,2
503471,52.172396,-3.337343,04/02/2022,60,6,14:36,3,481,13,4,6,0,0,1,1,1,0,2
503472,51.998470,-3.284127,22/07/2022,60,6,15:15,3,470,16,4,3,438,0,1,1,1,0,2
503473,52.630192,-3.163807,27/01/2023,60,6,06:45,3,483,0,-1,0,-1,0,2,1,6,0,2
503474,52.703260,-3.179130,24/06/2024,60,6,17:00,3,490,13,4,6,0,0,1,1,1,13,2

In [12]:
df1["date"] = pd.to_datetime(df1["date"],format="%d/%m/%Y")

/var/folders/qt/8w5zy69d4c3_bvqdvxnrx3fw0000gn/T/ipykernel_87551/870136501.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["date"] = pd.to_datetime(df1["date"],format="%d/%m/%Y")

In [13]:
df1["time"] = pd.to_datetime(df1["time"], format="%H:%M").dt.time

/var/folders/qt/8w5zy69d4c3_bvqdvxnrx3fw0000gn/T/ipykernel_87551/411002257.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["time"] = pd.to_datetime(df1["time"], format="%H:%M").dt.time

In [14]:
df1

,latitude,longitude,date,speed_limit,road_type,time,first_road_class,first_road_number,junction_detail,junction_control,second_road_class,second_road_number,pedestrian_crossing,road_surface_conditions,weather_conditions,light_conditions,carriageway_hazards,urban_or_rural_area
0,54.689833,-1.270905,2021-05-22,60,6,22:44:00,6,0,0,-1,0,-1,0,1,1,6,0,2
1,54.690592,-1.218333,2021-10-20,30,6,15:50:00,4,1277,16,2,5,0,0,1,1,1,0,1
2,54.570397,-1.232884,2020-12-01,20,6,18:00:00,6,0,16,4,6,0,0,1,1,4,0,1
3,54.520825,-1.233040,2021-12-09,40,6,16:55:00,5,0,0,-1,0,-1,0,2,1,4,0,2
4,54.580641,-1.290292,2021-04-12,70,3,09:02:00,3,19,0,-1,0,-1,0,1,1,1,13,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503470,52.034574,-3.199828,2021-09-11,60,6,01:15:00,6,0,0,-1,0,-1,0,1,1,6,0,2
503471,52.172396,-3.337343,2022-02-04,60,6,14:36:00,3,481,13,4,6,0,0,1,1,1,0,2
503472,51.998470,-3.284127,2022-07-22,60,6,15:15:00,3,470,16,4,3,438,0,1,1,1,0,2
503473,52.630192,-3.163807,2023-01-27,60,6,06:45:00,3,483,0,-1,0,-1,0,2,1,6,0,2
503474,52.703260,-3.179130,2024-06-24,60,6,17:00:00,3,490,13,4,6,0,0,1,1,1,13,2

In [15]:
df1["day_of_week"]=df1['date'].dt.dayofweek

/var/folders/qt/8w5zy69d4c3_bvqdvxnrx3fw0000gn/T/ipykernel_87551/3117067752.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["day_of_week"]=df1['date'].dt.dayofweek

In [16]:
df1["month"] = df1["date"].dt.month

/var/folders/qt/8w5zy69d4c3_bvqdvxnrx3fw0000gn/T/ipykernel_87551/3027078628.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["month"] = df1["date"].dt.month

In [17]:
df1["hour_of_day"] = pd.to_datetime(df1["time"].astype(str)).dt.hour

/var/folders/qt/8w5zy69d4c3_bvqdvxnrx3fw0000gn/T/ipykernel_87551/3625710572.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df1["hour_of_day"] = pd.to_datetime(df1["time"].astype(str)).dt.hour
/var/folders/qt/8w5zy69d4c3_bvqdvxnrx3fw0000gn/T/ipykernel_87551/3625710572.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["hour_of_day"] = pd.to_datetime(df1["time"].astype(str)).dt.hour

In [18]:
df1["is_weekend"]=df1["day_of_week"].isin([5,6]).astype(int)

/var/folders/qt/8w5zy69d4c3_bvqdvxnrx3fw0000gn/T/ipykernel_87551/850445247.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["is_weekend"]=df1["day_of_week"].isin([5,6]).astype(int)

In [19]:
df1["is_night"] = ((df1["hour_of_day"] < 6) | (df1["hour_of_day"] > 20)).astype(int)

/var/folders/qt/8w5zy69d4c3_bvqdvxnrx3fw0000gn/T/ipykernel_87551/1121623552.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["is_night"] = ((df1["hour_of_day"] < 6) | (df1["hour_of_day"] > 20)).astype(int)

In [20]:
df1

,latitude,longitude,date,speed_limit,road_type,time,first_road_class,first_road_number,junction_detail,junction_control,...,road_surface_conditions,weather_conditions,light_conditions,carriageway_hazards,urban_or_rural_area,day_of_week,month,hour_of_day,is_weekend,is_night
0,54.689833,-1.270905,2021-05-22,60,6,22:44:00,6,0,0,-1,...,1,1,6,0,2,5,5,22,1,1
1,54.690592,-1.218333,2021-10-20,30,6,15:50:00,4,1277,16,2,...,1,1,1,0,1,2,10,15,0,0
2,54.570397,-1.232884,2020-12-01,20,6,18:00:00,6,0,16,4,...,1,1,4,0,1,1,12,18,0,0
3,54.520825,-1.233040,2021-12-09,40,6,16:55:00,5,0,0,-1,...,2,1,4,0,2,3,12,16,0,0
4,54.580641,-1.290292,2021-04-12,70,3,09:02:00,3,19,0,-1,...,1,1,1,13,2,0,4,9,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503470,52.034574,-3.199828,2021-09-11,60,6,01:15:00,6,0,0,-1,...,1,1,6,0,2,5,9,1,1,1
503471,52.172396,-3.337343,2022-02-04,60,6,14:36:00,3,481,13,4,...,1,1,1,0,2,4,2,14,0,0
503472,51.998470,-3.284127,2022-07-22,60,6,15:15:00,3,470,16,4,...,1,1,1,0,2,4,7,15,0,0
503473,52.630192,-3.163807,2023-01-27,60,6,06:45:00,3,483,0,-1,...,2,1,6,0,2,4,1,6,0,0
503474,52.703260,-3.179130,2024-06-24,60,6,17:00:00,3,490,13,4,...,1,1,1,13,2,0,6,17,0,0

In [21]:
import h3

In [22]:
res=8

In [23]:
df1["h3_cell"]=df1.apply(lambda r:h3.latlng_to_cell(r["latitude"], r["longitude"],res), axis=1)

/var/folders/qt/8w5zy69d4c3_bvqdvxnrx3fw0000gn/T/ipykernel_87551/2706331462.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["h3_cell"]=df1.apply(lambda r:h3.latlng_to_cell(r["latitude"], r["longitude"],res), axis=1)

In [24]:
df1

,latitude,longitude,date,speed_limit,road_type,time,first_road_class,first_road_number,junction_detail,junction_control,...,weather_conditions,light_conditions,carriageway_hazards,urban_or_rural_area,day_of_week,month,hour_of_day,is_weekend,is_night,h3_cell
0,54.689833,-1.270905,2021-05-22,60,6,22:44:00,6,0,0,-1,...,1,6,0,2,5,5,22,1,1,8819465741fffff
1,54.690592,-1.218333,2021-10-20,30,6,15:50:00,4,1277,16,2,...,1,1,0,1,2,10,15,0,0,881946cd95fffff
2,54.570397,-1.232884,2020-12-01,20,6,18:00:00,6,0,16,4,...,1,4,0,1,1,12,18,0,0,88194654e3fffff
3,54.520825,-1.233040,2021-12-09,40,6,16:55:00,5,0,0,-1,...,1,4,0,2,3,12,16,0,0,881946465bfffff
4,54.580641,-1.290292,2021-04-12,70,3,09:02:00,3,19,0,-1,...,1,1,13,2,0,4,9,0,0,88194655d5fffff
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503470,52.034574,-3.199828,2021-09-11,60,6,01:15:00,6,0,0,-1,...,1,6,0,2,5,9,1,1,1,88195e26a7fffff
503471,52.172396,-3.337343,2022-02-04,60,6,14:36:00,3,481,13,4,...,1,1,0,2,4,2,14,0,0,88195e22e3fffff
503472,51.998470,-3.284127,2022-07-22,60,6,15:15:00,3,470,16,4,...,1,1,0,2,4,7,15,0,0,88195e2591fffff
503473,52.630192,-3.163807,2023-01-27,60,6,06:45:00,3,483,0,-1,...,1,6,0,2,4,1,6,0,0,88195eba2dfffff
503474,52.703260,-3.179130,2024-06-24,60,6,17:00:00,3,490,13,4,...,1,1,13,2,0,6,17,0,0,88195e85edfffff

In [25]:
cell_counts=df1.groupby("h3_cell").size().rename("accident_count_cell")

In [26]:
df1 = df1.join(cell_counts, on="h3_cell")

In [27]:
df1

,latitude,longitude,date,speed_limit,road_type,time,first_road_class,first_road_number,junction_detail,junction_control,...,light_conditions,carriageway_hazards,urban_or_rural_area,day_of_week,month,hour_of_day,is_weekend,is_night,h3_cell,accident_count_cell
0,54.689833,-1.270905,2021-05-22,60,6,22:44:00,6,0,0,-1,...,6,0,2,5,5,22,1,1,8819465741fffff,1
1,54.690592,-1.218333,2021-10-20,30,6,15:50:00,4,1277,16,2,...,1,0,1,2,10,15,0,0,881946cd95fffff,29
2,54.570397,-1.232884,2020-12-01,20,6,18:00:00,6,0,16,4,...,4,0,1,1,12,18,0,0,88194654e3fffff,59
3,54.520825,-1.233040,2021-12-09,40,6,16:55:00,5,0,0,-1,...,4,0,2,3,12,16,0,0,881946465bfffff,13
4,54.580641,-1.290292,2021-04-12,70,3,09:02:00,3,19,0,-1,...,1,13,2,0,4,9,0,0,88194655d5fffff,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503470,52.034574,-3.199828,2021-09-11,60,6,01:15:00,6,0,0,-1,...,6,0,2,5,9,1,1,1,88195e26a7fffff,2
503471,52.172396,-3.337343,2022-02-04,60,6,14:36:00,3,481,13,4,...,1,0,2,4,2,14,0,0,88195e22e3fffff,2
503472,51.998470,-3.284127,2022-07-22,60,6,15:15:00,3,470,16,4,...,1,0,2,4,7,15,0,0,88195e2591fffff,8
503473,52.630192,-3.163807,2023-01-27,60,6,06:45:00,3,483,0,-1,...,6,0,2,4,1,6,0,0,88195eba2dfffff,3
503474,52.703260,-3.179130,2024-06-24,60,6,17:00:00,3,490,13,4,...,1,13,2,0,6,17,0,0,88195e85edfffff,1

In [28]:
df1.columns

Index(['latitude', 'longitude', 'date', 'speed_limit', 'road_type', 'time',
       'first_road_class', 'first_road_number', 'junction_detail',
       'junction_control', 'second_road_class', 'second_road_number',
       'pedestrian_crossing', 'road_surface_conditions', 'weather_conditions',
       'light_conditions', 'carriageway_hazards', 'urban_or_rural_area',
       'day_of_week', 'month', 'hour_of_day', 'is_weekend', 'is_night',
       'h3_cell', 'accident_count_cell'],
      dtype='object')

In [29]:
cell_day=df1.groupby(['h3_cell','date']).size().reset_index(name='accidents_today')

In [30]:
start=cell_day["date"].min()
end=cell_day["date"].max()

In [31]:
full_dates=pd.date_range(start,end,freq='D').date

In [32]:
cells=cell_day['h3_cell'].unique()

In [33]:
full = pd.MultiIndex.from_product([cells, full_dates],names=['h3_cell','date']).to_frame().reset_index(drop=True)

In [34]:
full

                   h3_cell        date
0          8809a44713fffff  2020-01-01
1          8809a44713fffff  2020-01-02
2          8809a44713fffff  2020-01-03
3          8809a44713fffff  2020-01-04
4          8809a44713fffff  2020-01-05
...                    ...         ...
144314725  881976dac1fffff  2024-12-27
144314726  881976dac1fffff  2024-12-28
144314727  881976dac1fffff  2024-12-29
144314728  881976dac1fffff  2024-12-30
144314729  881976dac1fffff  2024-12-31

[144314730 rows x 2 columns]

In [35]:
cell_day['date'] = pd.to_datetime(cell_day['date']).dt.date
full['date'] = pd.to_datetime(full['date']).dt.date

KeyboardInterrupt:

In [ ]:
full = full.merge(cell_day,on=['h3_cell','date'],how='left')

In [ ]:
window=7
full['accidents_today'] = full['accidents_today'].fillna(0)
full=full.sort_values(['h3_cell','date'])

In [ ]:
full['future_accidents'] = (
    full
    .groupby('h3_cell')['accidents_today']
    .apply(lambda s: s.shift(-1).rolling(window=window, min_periods=1).sum())
    .reset_index(level=0, drop=True)
)

In [ ]:
full['label']=(full['future_accidents']>0).astype(int)
full=full.dropna(subset=['future_accidents']).reset_index(drop=True)

In [ ]:
cell_attrs = df1.groupby('h3_cell').agg({
    'speed_limit': 'first',
    'road_type': 'first',
    'first_road_class': 'first',
    'first_road_number': 'first',
    'junction_detail': 'first',
    'junction_control': 'first',
    'second_road_class': 'first',
    'second_road_number': 'first',
    'pedestrian_crossing': 'first',
    'road_surface_conditions': 'first',
    'weather_conditions': 'first',
    'light_conditions': 'first',
    'carriageway_hazards': 'first',
    'urban_or_rural_area': 'first'
}).reset_index()

In [ ]:
full = full.merge(cell_attrs, on='h3_cell', how='left')

In [ ]:
full['day_of_week'] = pd.to_datetime(full['date']).dt.dayofweek
full['month'] = pd.to_datetime(full['date']).dt.month
full['is_weekend'] = full['day_of_week'].isin([5,6]).astype(int)
full['is_night'] = 0

In [ ]:
full['acc_last_7'] = full.groupby('h3_cell')['accidents_today'].transform(
    lambda s: s.rolling(7, min_periods=1).sum().shift(1).fillna(0)
)
full['acc_last_30'] = full.groupby('h3_cell')['accidents_today'].transform(
    lambda s: s.rolling(30, min_periods=1).sum().shift(1).fillna(0)
)

In [ ]:
full.info()

In [ ]:
unique_count = full['label'].nunique()

In [ ]:
unique_count

In [ ]:
import pandas as pd, numpy as np, gc
from math import ceil
BATCH_SIZE = 5000
OUT_DIR = "train_chunks_parquet"   # directory to write parts

agg_cols = [
    'h3_cell','speed_limit','road_type','first_road_class','first_road_number',
    'junction_detail','junction_control','second_road_class','second_road_number',
    'pedestrian_crossing','road_surface_conditions','weather_conditions',
    'light_conditions','carriageway_hazards','urban_or_rural_area'
]
cols = [c for c in agg_cols if c in df1.columns]

df_small = df1[cols].copy()

def mode_or_first(s):
    m = s.mode()
    return m.iloc[0] if not m.empty else s.iloc[0]


cell_attrs = df_small.groupby('h3_cell').agg(mode_or_first).reset_index()

for c in cell_attrs.select_dtypes(include=['object']).columns:
    cell_attrs[c] = cell_attrs[c].astype('category')

print("cell_attrs shape:", cell_attrs.shape)
print(cell_attrs.head())
maps = {}
for col in cell_attrs.columns:
    if col == 'h3_cell':
        continue
    maps[col] = cell_attrs.set_index('h3_cell')[col].to_dict()

import os
os.makedirs(OUT_DIR, exist_ok=True)

unique_cells = label_df['h3_cell'].unique()
n_batches = ceil(len(unique_cells) / BATCH_SIZE)
print(f"Unique cells: {len(unique_cells)}, batches: {n_batches}")

for i in range(0, len(unique_cells), BATCH_SIZE):
    batch_cells = unique_cells[i:i + BATCH_SIZE]
   
    chunk = label_df[label_df['h3_cell'].isin(batch_cells)].copy()

    for col, m in maps.items():
        
        chunk[col] = chunk['h3_cell'].map(m)

    part_path = os.path.join(OUT_DIR, f"part_{i//BATCH_SIZE:04d}.parquet")
    chunk.to_parquet(part_path, index=False)

    print(f"Wrote {part_path} rows={len(chunk)}")
    # free memory
    del chunk
    gc.collect()

print("All batches written to", OUT_DIR)